version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: [ "18.x" ]
  - package-ecosystem: npm
    directory: "/e2e"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: [ "18.x" ]
  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: [ "18.x" ]
