name: Généaplanner pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Get changed files in the e2e folder
        id: changed-files-e2e
        uses: tj-actions/changed-files@main
        with:
          files: e2e
      -
        name: Get changed files in the frontend folder
        id: changed-files-frontend
        uses: tj-actions/changed-files@main
        with:
          files: frontend
      -
        name: Get changed files in the backend folder
        id: changed-files-backend
        uses: tj-actions/changed-files@main
        with:
          files: backend
      -
        name: Setup Node JS
        uses: actions/setup-node@main
        with:
          node-version: 16.18.1
      -
        name: Build backend
        if: steps.changed-files-backend.outputs.any_changed == 'true'
        run: |
          npm install
          npm test
        working-directory: backend
      -
        name: Prepare frontend
        if: steps.changed-files-frontend.outputs.any_changed == 'true'
        run: npm install --force
        working-directory: frontend
      -
        name: Deploy backend on dev
        if: steps.changed-files-backend.outputs.any_changed == 'true'
        run: npm run deploy-dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: backend
      -
        name: Deploy frontend on dev
        if: steps.changed-files-frontend.outputs.any_changed == 'true'
        run: npm run deploy-dev
        env:
          OAUTH0_DEV_CLIENT_ID: ${{ secrets.OAUTH0_DEV_CLIENT_ID }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        working-directory: frontend
      -
        name: Prepare end-to-end-tests
        if: steps.changed-files-e2e.outputs.any_changed == 'true'
        run: npm install
        working-directory: e2e
      -
        name: Run end-to-end tests
        if: steps.changed-files-backend.outputs.any_changed == 'true' || steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-e2e.outputs.any_changed == 'true'
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: https://geneaplanner-dev.surge.sh
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          AUTH0_API_CLIENT_ID: ${{ secrets.AUTH0_API_CLIENT_ID }}
          AUTH0_API_CLIENT_SECRET: ${{ secrets.AUTH0_API_CLIENT_SECRET }}
        with:
          browser: chrome
          working-directory: e2e
      -
        name: Deploy backend on prod
        if: steps.changed-files-backend.outputs.any_changed == 'true'
        run: npm run deploy-prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: backend
